apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "k8s1"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "k8s1"
    spec:
      containers:
        - name: "k8s1"
          image: "amlws3a6c9fca.azurecr.io/k8s1"
          ports:
          - containerPort: 80