apiVersion: v1
kind: Service
metadata:
    name: "devaksjurainc-2304"
    labels:
        app: "devaksjurainc-2304"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "devaksjurainc-2304"