on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: devamlacrjurainc.azurecr.io
        username: ${{ secrets.acr_devamlacrjurainc_username }}
        password: ${{ secrets.acr_devamlacrjurainc_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t devamlacrjurainc.azurecr.io/devaksjurainc:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push devamlacrjurainc.azurecr.io/devaksjurainc:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_devaksjurainc_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep dev-aks-juraincb9b0 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace dev-aks-juraincb9b0`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: dev-aks-juraincb9b0
        container-registry-url: devamlacrjurainc.azurecr.io
        container-registry-username: ${{ secrets.acr_devamlacrjurainc_username }}
        container-registry-password: ${{ secrets.acr_devamlacrjurainc_password }}
        secret-name: devaksjuraindockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: dev-aks-juraincb9b0
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          devamlacrjurainc.azurecr.io/devaksjurainc:${{ github.sha }}
        imagepullsecrets: |
          devaksjuraindockerauth
