on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: amlws3a6c9fca.azurecr.io
        username: ${{ secrets.acr_amlws3a6c9fca_username }}
        password: ${{ secrets.acr_amlws3a6c9fca_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t amlws3a6c9fca.azurecr.io/k8s1:${{ github.sha }}
        docker push amlws3a6c9fca.azurecr.io/k8s1:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_k8s1_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep k8s1ca2c | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace k8s1ca2c`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: k8s1ca2c
        container-registry-url: amlws3a6c9fca.azurecr.io
        container-registry-username: ${{ secrets.acr_amlws3a6c9fca_username }}
        container-registry-password: ${{ secrets.acr_amlws3a6c9fca_password }}
        secret-name: k8s1dockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: k8s1ca2c
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          amlws3a6c9fca.azurecr.io/k8s1:${{ github.sha }}
        imagepullsecrets: |
          k8s1dockerauth